baseURL       = "https://igem.berkeley.edu/"
languageCode  = "en-us"
title         = "iGEM at Berkeley"
theme         = "roxo"
summarylength = 10

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Community"
    url     = "community"
    weight  = 2
  [[menu.nav]]
    name    = "Outreach"
    url     = "outreach"
    weight  = 3
  [[menu.nav]]
    name    = "Finance"
    url     = "finance"
    weight  = 4
  [[menu.nav]]
    name    = "Experimental Teams"
    url     = "experimental"
    weight  = 5
  [[menu.nav]]
    name    = "DeCal"
    url     = "feb"
    weight  = 6
  [[menu.nav]]
    name    = "Join iGEM"
    url     = "recruitment"
    weight  = 7

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "iGEM at Berkeley"
  author = "iGEM at Berkeley"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Join Us"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/retreat.png"
    heading               = "Join us for undergrad-led synthetic biology research, training programs, and a large community of aspiring scientists!"
    tagline               = "iGEM at Berkeley"
    primary_button        = "Join an iGEM team today!"
    primary_button_url    = "https://igem.berkeley.edu/recruitment/"
    secondary_button      = "Graduate Student Mentors"
    secondary_button_url  = "http://bit.ly/igemgradmentor"

  [params.portfolio]
    enable    = true
    title     = "OUR TEAMS"
    subtitle  = "Take a look at our Wetlab and Computational Biology teams."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "GET INVOLVED"
    primary_button      = "Apply to Experimental/New Ideas Team"
    primary_button_url  = "https://docs.google.com/forms/d/e/1FAIpQLSc4kUSmc6TNFonkDwzAppapGv4q64xXsdXETc97yCoA8jOfSA/viewform?usp=sf_link"
    secondary_button    = "Enroll in our lab DeCal"
    secondary_button_url = "https://decal.berkeley.edu/courses/"
    finance_primary_button      = "Join Our Team"
    finance_primary_button_url  = "finance-join-our-team"
    finance_secondary_button    = "Be A Partner"
    finance_secondary_button_url = "finance-be-a-partner"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Us"
      address = "University of California, Berkeley"
      phone   = "directors@igem.berkeley.edu"
      email   = ""
      # Footer Site Map
      [params.footer.sitemap]
        title   = "Site Map"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Community"
          url  = "community"
        [[params.footer.sitemap.link]]
          name = "Outreach"
          url  = "outreach"
        [[params.footer.sitemap.link]]
          name = "Finance"
          url  = "finance"
        [[params.footer.sitemap.link]]
          name = "Experimental Teams"
          url  = "experimental"
        [[params.footer.sitemap.link]]
          name = "DeCal"
          url  = "feb"
        [[params.footer.sitemap.link]]
          name = "Project Proposals"
          url  = "proposals"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/igematberkeley"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/igematberk/"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/igematberkeley"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/igematberkeley"
      # Footer Service
      [params.footer.service]
        title       = "Student Group Disclaimer:"
        description = "We are a student group acting independently of the University of California. We take full responsibility for our organization and this web site."