baseURL       = "http://igem.berkeley.edu/"
languageCode  = "en-us"
title         = "iGEM at Berkeley"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  # [[menu.nav]]
    # name    = "Projects"
    # url     = "portfolio"
    # weight  = 2
  [[menu.nav]]
    name    = "Experimental Teams"
    url     = "blog"
    weight  = 2
  [[menu.nav]]
    name    = "Training"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Finance"
    url     = "portfolio"
    weight  = 4
  [[menu.nav]]
    name    = "Community"
    url     = "portfolio"
    weight  = 5
  [[menu.nav]]
    name    = "Join Us"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Join Us"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/retreat.jpg"
    heading               = "We are committed to synthetic biology research for students, by students. Join us for undergrad-led research, training programs, and a whole community of aspiring scientists!"
    tagline               = "iGEM at Berkeley"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR TEAMS"
    subtitle  = "Take a look at our Wetlab and Computational Biology teams."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Us"
      address = "University of California, Berkeley"
      phone   = "818-731-9925"
      email   = "directors@igem.berkeley.edu"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/igematberkeley"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/igematberk/"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/igematberkeley"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/igematberkeley"
      # Footer Service
      [params.footer.service]
        title       = "Student Group Disclaimer:"
        description = "We are a student group acting independently of the University of California. We take full responsibility for our organization and this web site."